# Generated by Django 4.2.3 on 2023-07-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='Password',
            field=models.CharField(max_length=252),
        ),
    ]
