# Generated by Django 4.2.3 on 2023-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploadimage')),
                ('title', models.CharField(max_length=25)),
                ('text', models.TextField(max_length=50)),
            ],
        ),
    ]
